### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by wingmatt** [wingmatt/blatherbrush-nextjs#13]
### User Stories

As a site owner, I want to have good unit test code coverage, so that I can confidently refactor the app without fearing the introduction of unintended side effects or regressions.

### Acceptance Criteria:
- [ ] Demonstrate that the `lobbyActions.ts` is 100% covered by Jest unit tests.
- [ ] Demonstrate that the `playerActions.ts` is 100% covered by Jest unit tests.
- [ ] Demonstrate that the `promptActions.ts` is 100% covered by Jest unit tests.
- [ ] Demonstrate that the `useUserData` function within `UserProvider.tsx` has a corresponding mock function that provides a predictable data set for performing unit tests.
- [ ] Demonstrate that each component is covered by at least one unit test which uses Jest and React Testing Library to test its display and interaction(s).

**Comment by wingmatt** [comment]
The big challenge right off the bat is mocking Supabase. When running unit tests, I keep getting the following error for all of them:

```
Test suite failed to run

    supabaseUrl is required.

      4 | const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
      5 |
    > 6 | export const supabase = createClient(supabaseUrl, supabaseAnonKey)
        |                                     ^
      7 |
      8 | export const insertAndReturn = async (table, newData) => {
      9 |   try {

      at new SupabaseClient (node_modules/@supabase/supabase-js/src/SupabaseClient.ts:88:29)
      at createClient (node_modules/@supabase/supabase-js/src/index.ts:38:10)
      at Object.<anonymous> (src/helpers/supabaseClient.js:6:37)
      at Object.<anonymous> (src/helpers/lobbyActions.ts:34:25)
      at Object.<anonymous> (src/components/StartForm.tsx:15:23)
      at Object.<anonymous> (src/components/StartForm.test.js:8:59)
```

I'm thinking this is due to Jest not having access to the NextJS environment variables, causing the instantiation to fail, but I don't want it to succeed and actually create a Supabase connection and make database calls for each unit test.

I'd rather create mocks that skip any sort of Supabase connection, and instead return predictable values. I did this with a simpler use case in an earlier project with [Manual Mocks](https://jestjs.io/docs/manual-mocks) - I mocked the entire supabase instance to return the same values each time.

I think I'd rather mock the basic action functions, such as [getLobbyData](https://github.com/wingmatt/blatherbrush-nextjs/blob/095803321dfa69756a45d8dbb667a3a1e7485c43/src/helpers/lobbyActions.ts#LL5C1-L26C3), since these should remain fairly straightforward and (hopefully) won't need unit tests to prevent issues from creeping up.

For mocking OpenAI API calls, I'm thinking [this dev.to article](https://dev.to/zaklaughton/the-only-3-steps-you-need-to-mock-an-api-call-in-jest-39mb) might be worth following.

**Comment by wingmatt** [comment]
Creating the mocks using the Manual Mock method (or the `jest.fn` method) didn't seem to actually change the behavior of the tests, almost like the mocks weren't being loaded at all.

After some digging I found that Jest mocks are a bit weirder if you use `import` instead of `require` to access a module, especially within the project.

- [Jest GH issue about module mocking](https://github.com/jestjs/jest/issues/10025)
- [Jest status tracker for native ES Modules support](https://github.com/jestjs/jest/issues/9430)
- [Jest docs about module mocking](https://jestjs.io/docs/ecmascript-modules#module-mocking-in-esm)

Hopefully this really is the core issue and everything will Just Work after finding a good way around it. It would explain why my mocks don't seem to be doing much of anything yet!

Possible next steps:
- Fiddle with how Babel compiles the tests to the point where it formats the compiled code in a way that supports mocking (ugh)
- Confirm that `node_modules` modules can still be mocked, and mock them instead (possibly a lot of weird boilerplate)
- Use one of the methods in development to bypass all of this (possibly buggy), like `jest.unstable_mockModule`

**Comment by wingmatt** [comment]
Trying the Babel compilation configuration step I mentioned in [this branch](https://github.com/wingmatt/blatherbrush-nextjs/tree/add-unit-tests).

In my internet travels, I found out that Next now uses a custom Rust-based compiler for Jest stuff  by default, which doesn't allow for some of the things like `jest.unstable_mockModule` or workarounds like [this testing format](https://github.com/connorjburton/js-ts-jest-esm-mock/blob/main/js/index.test.js) (Next's compiler doesn't allow you to `await` imports). So I switched the test compiler from Next's custom thing to a more universal Babel config.

The [branch](https://github.com/wingmatt/blatherbrush-nextjs/tree/add-unit-tests) is still mostly failing tests where they even exist, but now the tests fail because I haven't built out all of the mocks to handle the app's DB/API calls, instead of it being impossible to mock anything. I'm calling that a win for right now 🎉
